### PR TITLE
Reset feature implemented

### LINKED ISSUE #2: Button to reset all active column-based filters
A user might filter based on multiple columns but then want to go back to a state without filters. Currently, they need to click the "Reset" button for each of the applied filters, but it might be good if there was a separate button to reset all the column fitlers. It probably should be somewhere near the head of the table, e.g. next to the hint button.

### PR DESCRIPTION
**Pull request by SharanRP**
closes #2 

Reset Button has been implemented 
image
On clicking Reset Button
image

any suggestion on icon of reset button ? and is margin proper or should have same margin as ```show columns``` button?

### CODE REVIEW

**Review by eimrek — CHANGES_REQUESTED** [review]
Thanks a lot @SharanRP. The functionality seems to work well. Could you make just some small reorganizational/formatting changes:
* could the ResetButton.js/css be moved to /MaterialDataGrid folder?
* could the resetbutton be located to the left of the help button.
* could the resetbutton be disabled/grayed out if no column filter is present?
* could the styling of the resetbutton be similar to the active column filter indicator button (the small blue circle). Basically it could perhaps be the same blue color and have curved corners.
* could the text be "reset column filters" (possibly on 2 lines)?

**Comment by eimrek** [comment]
Maybe something like this: 
image

But i'm thinking it should be completely gray (no blue tone at all) if there is no active column filter. But no need to be perfect now, i can tweak it myself after we merge this.

**Comment by SharanRP** [comment]
Sure , I am working on it

**Comment by SharanRP** [comment]
I have updated the files @eimrek

**Review by eimrek — CHANGES_REQUESTED** [review]
Thanks @SharanRP!

One issue:
* currently, if the periodic table filter is active, the "Reset column filters" button also becomes active, although there are no column filters active. Could this be fixed such that it's only active if there are column filters?

A minor formatting thing:
* After slight reconsideration, i think it's better if the reset button is to the right of the help button. So that we have in order: help - reset filters - show columns.
* and now thinking about it, could the button look exactly the same as the "show columns" button? (same size, padding, placement, no corner curvature)

**Comment by SharanRP** [comment]
I have updated the styling, but I am confused about why the Reset button becomes active when filtering the periodic table

**Comment by eimrek** [comment]
Finally had time to clean this up. now works well. thanks @SharanRP!

**Pull request merged**
